/home/exouser/YuZheng/experiments/autoencoder_kl_gan/world_size1-hmdb_autoencoder
load yaml from config
Launching processes...
2025-02-06 16:02:20,532 train INFO: Building config ...
2025-02-06 16:02:20,532 train INFO: Building dataloaders ...
Total frames in dataset: 186436
2025-02-06 16:03:17,798 train INFO: Train dataloaders build complete
Total frames in dataset: 186436
2025-02-06 16:04:15,354 train INFO: Valid dataloaders build complete
2025-02-06 16:04:15,354 train INFO: Building models ...
2025-02-06 16:04:16,070 train INFO: finetune checkpoint path not exist
2025-02-06 16:04:16,273 train INFO: params autoencoder_kl: 55912619
2025-02-06 16:04:16,273 train INFO: params lpipsWithDisc: 2765634
2025-02-06 16:04:16,273 train INFO: begin training ...
Traceback (most recent call last):
  File "/home/exouser/YuZheng/train.py", line 179, in <module>
    main(args)
  File "/home/exouser/YuZheng/train.py", line 153, in main
    subprocess_fn(args)
  File "/home/exouser/YuZheng/train.py", line 78, in subprocess_fn
    model_without_ddp.trainer(train_dataloader, valid_dataloader, builder.get_max_epoch(), builder.get_max_step(), checkpoint_savedir=args.relative_checkpoint_dir if model_without_ddp.use_ceph else args.run_dir, resume=args.resume)
  File "/home/exouser/YuZheng/models/model.py", line 424, in trainer
    self._iter_trainer(train_data_loader, test_data_loader, max_steps) 
  File "/home/exouser/YuZheng/models/model.py", line 464, in _iter_trainer
    for step in range(self.begin_step, max_steps):
  File "/home/exouser/anaconda3/envs/yuzhengood/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1928, in __getattr__
    raise AttributeError(
AttributeError: 'autoencoder_kl_gan_model' object has no attribute 'begin_step'
